/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AlertInfo: typeof import('./components/AlertInfo.vue')['default']
    Combobox: typeof import('@headlessui/vue')['Combobox']
    ComboboxButton: typeof import('@headlessui/vue')['ComboboxButton']
    ComboboxInput: typeof import('@headlessui/vue')['ComboboxInput']
    ComboboxOption: typeof import('@headlessui/vue')['ComboboxOption']
    ComboboxOptions: typeof import('@headlessui/vue')['ComboboxOptions']
    ConfettiIcon: typeof import('./components/main/match/ConfettiIcon.vue')['default']
    Dialog: typeof import('@headlessui/vue')['Dialog']
    DialogOverlay: typeof import('@headlessui/vue')['DialogOverlay']
    DialogTitle: typeof import('@headlessui/vue')['DialogTitle']
    DogBreedChip: typeof import('./components/main/DogBreedChip.vue')['default']
    DogBreedsCombo: typeof import('./components/main/DogBreedsCombo.vue')['default']
    DogCard: typeof import('./components/main/DogCard.vue')['default']
    DogIcon: typeof import('./components/DogIcon.vue')['default']
    ErrorAlert: typeof import('./components/ErrorAlert.vue')['default']
    FavoriteDogCard: typeof import('./components/main/favorites/FavoriteDogCard.vue')['default']
    FavoritesModal: typeof import('./components/main/favorites/FavoritesModal.vue')['default']
    Filters: typeof import('./components/main/Filters.vue')['default']
    Hero: typeof import('./components/main/Hero.vue')['default']
    Login: typeof import('./components/auth/Login.vue')['default']
    MatchCard: typeof import('./components/main/match/MatchCard.vue')['default']
    MatchModal: typeof import('./components/main/match/MatchModal.vue')['default']
    Menu: typeof import('@headlessui/vue')['Menu']
    MenuButton: typeof import('@headlessui/vue')['MenuButton']
    MenuItem: typeof import('@headlessui/vue')['MenuItem']
    MenuItems: typeof import('@headlessui/vue')['MenuItems']
    Pagination: typeof import('./components/main/Pagination.vue')['default']
    Popover: typeof import('@headlessui/vue')['Popover']
    PopoverButton: typeof import('@headlessui/vue')['PopoverButton']
    PopoverPanel: typeof import('@headlessui/vue')['PopoverPanel']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TransitionChild: typeof import('@headlessui/vue')['TransitionChild']
    TransitionRoot: typeof import('@headlessui/vue')['TransitionRoot']
  }
}
